### ISSUE TITLE
Incorrect colormap

### ISSUE THREAD

**Issue by luisortizuriarte** [heidinsiah123/CLIM680#4]
In your figure, you only display a single colorbar. However, since you don't specify a set of contour levels in your contourf plots, the colormaps are being calculated for each panel independently. See our lesson on multi-panel plotting for a way to make consistent colormaps across all your panels:

https://github.com/prukutu/clim680-codes/blob/gh-pages/src/multipanel.ipynb

**Comment by heidinsiah123** [comment]
Okay, thank you. I'll check that.

**Comment by luisortizuriarte** [comment]
Fixed. CLosing issue
